### PR TITLE
Added Mage Revised Addition

### PR DESCRIPTION
**Pull request by jason-kerney**
Some minor cosmetic changes. All abilities loose 2 and gain 1. Changed bottom image to "dissolve" the way revised character sheet does. Renamed a few minor fields.

### CODE REVIEW

**Comment by jason-kerney** [comment]
BTW. If this is good, can you submit this to the "world of darkness" system, as well as "Mage: The Ascension" system on Obsidian Portal?

**Comment by ChainsawXIV** [comment]
Sorry to take so long getting to this.

There's one thing that needs to be updated: the DST slug (used by the system itself) needs to be set to the slug name you want to use for this sheet. Basically, replace "chainsawxiv_mage" everywhere with a unique name for each variation of the sheet.

The system doesn't support the same sheet on more than one system, and each sheet needs a unique slug. The work-around there is to have the same sheet submitted twice, once for each system, but that means it will need a different slug for each system it's going to work with.

For ease of tracking, the folder name that the sheet files are in should match it's slug.

**Comment by jason-kerney** [comment]
I am not sure I follow. I have previously changed all instances of ""chainsawxiv_mage" to ""chainsawxiv_mage_revised". Are you telling me to submit the sheet?

Are you asking me to make a copy of the sheet for both systems?

Sorry for the delay. 

Thanks.

**Comment by ChainsawXIV** [comment]
My bad - I must not have been looking at the final commit. Sorry for the confusion.

**Comment by JKerney-HunterIndustries** [comment]
Thanks

**Comment by jason-kerney** [comment]
Hey I just used the sheet. I wanted to thank you again for uploading it.

**Pull request merged**
